# Generated by Django 5.1.6 on 2025-03-12 22:06

import drive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=None, upload_to=drive.models.user_directory_path),
            preserve_default=False,
        ),
    ]
