# Generated by Django 5.1.6 on 2025-03-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0002_file_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="size",
        ),
        migrations.AlterField(
            model_name="file",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
