# Generated by Django 5.1.6 on 2025-05-10 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0006_alter_file_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid folder name', regex='^[a-zA-Z0-9_-.]+$')]),
        ),
    ]
