# Generated by Django 5.1.6 on 2025-05-19 05:01

import django.core.validators
import django.db.models.deletion
import drive.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0008_alter_folder_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created_at'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Folder', 'verbose_name_plural': 'Folders'},
        ),
        migrations.AddField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, editable=False, help_text='Automatically detected MIME type of the file', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the file was uploaded'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text='The actual file to upload', upload_to=drive.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Folder where this file is stored', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='drive.folder'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the file', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, help_text='Display name for the file (defaults to original filename if not provided)', max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(editable=False, help_text='Size of the file in bytes'),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the folder was created'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the folder', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(help_text='Name of the folder. Allowed characters: letters, numbers, _, -, .', max_length=255, validators=[django.core.validators.RegexValidator(message='Folder name can only contain letters, numbers, underscores, hyphens, and periods', regex='^[a-zA-Z0-9_\\-\\.]+$')]),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, help_text='Parent folder if this is a subfolder', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='drive.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this folder', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('user', 'parent_folder', 'name')},
        ),
    ]
